"""add attachments table

Revision ID: 50529198cc8e
Revises: 77b3ba45c39a
Create Date: 2026-07-05 19:37:56.801121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50529198cc8e'
down_revision: Union[str, Sequence[str], None] = '77b3ba45c39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotency guards: databases bootstrapped with
    # Base.metadata.create_all already contain these objects; skip cleanly.
    _insp = sa.inspect(op.get_bind())
    _tables = set(_insp.get_table_names())

    def _cols(table):
        return {c["name"] for c in _insp.get_columns(table)} if table in _tables else set()

    def _idx(table):
        return {ix["name"] for ix in _insp.get_indexes(table)} if table in _tables else set()

    if 'attachments' in _tables:
        return
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_lead_id'), 'attachments', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_lead_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
