"""add follow up fields to lead

Revision ID: 77b3ba45c39a
Revises: f1e1afa48353
Create Date: 2026-07-05 19:04:10.751353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b3ba45c39a'
down_revision: Union[str, Sequence[str], None] = 'f1e1afa48353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotency guards: databases bootstrapped with
    # Base.metadata.create_all already contain these objects; skip cleanly.
    _insp = sa.inspect(op.get_bind())
    _tables = set(_insp.get_table_names())

    def _cols(table):
        return {c["name"] for c in _insp.get_columns(table)} if table in _tables else set()

    def _idx(table):
        return {ix["name"] for ix in _insp.get_indexes(table)} if table in _tables else set()

    for _col, _t in (
        ('last_contact_at', 'leads'),
        ('next_follow_up', 'leads'),
        ('deleted_at', 'leads'),
        ('deleted_at', 'tasks'),
    ):
        if _col not in _cols(_t):
            op.add_column(_t, sa.Column(_col, sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('leads', 'deleted_at')
    op.drop_column('leads', 'next_follow_up')
    op.drop_column('leads', 'last_contact_at')
    # ### end Alembic commands ###
