"""add soft delete to lead and task

Revision ID: f1e1afa48353
Revises: 8b8eab149c37
Create Date: 2026-07-05 18:34:21.434785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e1afa48353'
down_revision: Union[str, Sequence[str], None] = 'b0c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotency guards: databases bootstrapped with
    # Base.metadata.create_all already contain these objects; skip cleanly.
    _insp = sa.inspect(op.get_bind())
    _tables = set(_insp.get_table_names())

    def _cols(table):
        return {c["name"] for c in _insp.get_columns(table)} if table in _tables else set()

    def _idx(table):
        return {ix["name"] for ix in _insp.get_indexes(table)} if table in _tables else set()

    if 'is_deleted' not in _cols('leads'):
        op.add_column('leads', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # بقیه کدها ...
    if 'is_deleted' not in _cols('tasks'):
        op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: deleted_at is added/removed by 77b3ba45c39a, not here.
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('leads', 'is_deleted')
    # ### end Alembic commands ###
